name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: clctranspiler
  AZURE_FUNCTIONAPP_PACKAGE_PATH: clctranspiler

jobs:

  build:
    defaults:
      run:
        working-directory: clctranspiler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: ${{ github.event_name == 'push' }}

    - name: Deploy
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      if: ${{ github.event_name == 'push' }}
